version: '3.8'

services:
  # NestJS Application in development mode
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
      - '9229:9229' # Debug port
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql-dev
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=cinema_db_dev
      - JWT_SECRET=dev-jwt-secret
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mysql-dev:
        condition: service_healthy
    networks:
      - cinema-dev-network
    command: npm run start:debug

  # MySQL Database for development
  mysql-dev:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema_db_dev
    ports:
      - '3307:3306'
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - cinema-dev-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-dev
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - mysql-dev
    networks:
      - cinema-dev-network

volumes:
  mysql_dev_data:

networks:
  cinema-dev-network:
    driver: bridge
